import type { Team } from "@/src/types";

export const teams: Team[] = [
  {
    id: "t-platform",
    name: "Platform",
    description: "Core infrastructure, APIs, and developer tooling",
    leadId: "u-manager-1",
    memberIds: ["u-manager-1", "u-employee-1", "u-employee-4"],
    projectIds: ["p-command-center", "p-permissions", "p-api-gateway"],
    health: 92,
    workingDaysPerWeek: 5,
    velocity: 38,
  },
  {
    id: "t-growth",
    name: "Growth",
    description: "User acquisition, onboarding, and engagement",
    leadId: "u-manager-2",
    memberIds: ["u-manager-2", "u-employee-5", "u-employee-8"],
    projectIds: ["p-onboarding", "p-referral"],
    health: 86,
    workingDaysPerWeek: 5,
    velocity: 31,
  },
  {
    id: "t-design",
    name: "Design",
    description: "Product design, design systems, and brand identity",
    leadId: "u-manager-3",
    memberIds: ["u-manager-3", "u-employee-2", "u-employee-6"],
    projectIds: ["p-design-system", "p-dashboard-v2"],
    health: 94,
    workingDaysPerWeek: 5,
    velocity: 28,
  },
  {
    id: "t-qa",
    name: "Quality Assurance",
    description: "Test automation, regression, and release validation",
    leadId: "u-manager-4",
    memberIds: ["u-manager-4", "u-employee-3"],
    projectIds: ["p-test-automation"],
    health: 79,
    workingDaysPerWeek: 5,
    velocity: 24,
  },
  {
    id: "t-ops",
    name: "Operations",
    description: "Infrastructure, monitoring, and reliability",
    leadId: "u-admin-2",
    memberIds: ["u-admin-2", "u-employee-7"],
    projectIds: ["p-reporting", "p-monitoring"],
    health: 88,
    workingDaysPerWeek: 5,
    velocity: 32,
  },
];
