import type { User } from "@/src/types";

export const users: User[] = [
  // ── Admins ──────────────────────────────────────────────
  {
    id: "u-admin-1",
    name: "Maya Rao",
    role: "admin",
    title: "VP Operations",
    email: "maya.rao@workos.test",
    teamId: "t-platform",
    avatar: "MR",
    utilization: 78,
    performance: 94,
  },
  {
    id: "u-admin-2",
    name: "Vikram Joshi",
    role: "admin",
    title: "CTO",
    email: "vikram.joshi@workos.test",
    teamId: "t-ops",
    avatar: "VJ",
    utilization: 65,
    performance: 97,
  },

  // ── Managers ────────────────────────────────────────────
  {
    id: "u-manager-1",
    name: "Sourabh Yadav",
    role: "manager",
    title: "Engineering Manager",
    email: "sourabh.yadav@workos.test",
    teamId: "t-platform",
    avatar: "SY",
    utilization: 86,
    performance: 91,
  },
  {
    id: "u-manager-2",
    name: "Nora Shah",
    role: "manager",
    title: "Product Lead",
    email: "nora.shah@workos.test",
    teamId: "t-growth",
    avatar: "NS",
    utilization: 81,
    performance: 89,
  },
  {
    id: "u-manager-3",
    name: "Kabir Verma",
    role: "manager",
    title: "Design Lead",
    email: "kabir.verma@workos.test",
    teamId: "t-design",
    avatar: "KV",
    utilization: 74,
    performance: 92,
  },
  {
    id: "u-manager-4",
    name: "Priya Nair",
    role: "manager",
    title: "QA Lead",
    email: "priya.nair@workos.test",
    teamId: "t-qa",
    avatar: "PN",
    utilization: 79,
    performance: 88,
  },

  // ── Employees ───────────────────────────────────────────
  {
    id: "u-employee-1",
    name: "Dev Patel",
    role: "employee",
    title: "Frontend Engineer",
    email: "dev.patel@workos.test",
    teamId: "t-platform",
    avatar: "DP",
    utilization: 74,
    performance: 88,
  },
  {
    id: "u-employee-2",
    name: "Sara Khan",
    role: "employee",
    title: "Product Designer",
    email: "sara.khan@workos.test",
    teamId: "t-design",
    avatar: "SK",
    utilization: 69,
    performance: 92,
  },
  {
    id: "u-employee-3",
    name: "Ishan Bose",
    role: "employee",
    title: "QA Analyst",
    email: "ishan.bose@workos.test",
    teamId: "t-qa",
    avatar: "IB",
    utilization: 83,
    performance: 85,
  },
  {
    id: "u-employee-4",
    name: "Anika Gupta",
    role: "employee",
    title: "Backend Engineer",
    email: "anika.gupta@workos.test",
    teamId: "t-platform",
    avatar: "AG",
    utilization: 91,
    performance: 90,
  },
  {
    id: "u-employee-5",
    name: "Rohan Das",
    role: "employee",
    title: "Growth Analyst",
    email: "rohan.das@workos.test",
    teamId: "t-growth",
    avatar: "RD",
    utilization: 72,
    performance: 86,
  },
  {
    id: "u-employee-6",
    name: "Meera Iyer",
    role: "employee",
    title: "UI Engineer",
    email: "meera.iyer@workos.test",
    teamId: "t-design",
    avatar: "MI",
    utilization: 88,
    performance: 93,
  },
  {
    id: "u-employee-7",
    name: "Harsh Sharma",
    role: "employee",
    title: "DevOps Engineer",
    email: "harsh.sharma@workos.test",
    teamId: "t-ops",
    avatar: "HS",
    utilization: 80,
    performance: 87,
  },
  {
    id: "u-employee-8",
    name: "Tanya Singh",
    role: "employee",
    title: "Content Strategist",
    email: "tanya.singh@workos.test",
    teamId: "t-growth",
    avatar: "TS",
    utilization: 66,
    performance: 84,
  },
];
